language: cpp
cache:
  directories:
  - "$TRAVIS_BUILD_DIR/abc"
  - "$TRAVIS_BUILD_DIR/yosys"
  - "$TRAVIS_BUILD_DIR/ace2"
  - "$TRAVIS_BUILD_DIR/libs"
  - "$HOME/.ccache"
  - "$HOME/deps"
matrix:
  include:
  - os: linux
    sudo: false
    dist: bionic
    compiler: g++-8
    addons:
      apt:
        sources:
        - sourceline: ppa:ubuntu-toolchain-r/test
        packages:
        - autoconf
        - automake
        - bash
        - bison
        - build-essential
        - cmake
        - ctags
        - curl
        - doxygen
        - flex
        - fontconfig
        - g++-8
        - gcc-8
        - gdb
        - git
        - gperf
        - iverilog
        - libcairo2-dev
        - libevent-dev
        - libfontconfig1-dev
        - liblist-moreutils-perl
        - libncurses5-dev
        - libx11-dev
        - libxft-dev
        - libxml++2.6-dev
        - perl
        - python
        - texinfo
        - time
        - valgrind
        - zip
        - qt5-default
before_install:
- openssl aes-256-cbc -K $encrypted_6f6cf68308be_key -iv $encrypted_6f6cf68308be_iv -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- cp $TRAVIS_BUILD_DIR/deploy_key ~/.ssh/id_rsa
- echo -e "Host *\n  StrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh u1249762@lab1-1.eng.utah.edu pwd
- ssh u1249762@lab1-1.eng.utah.edu "mkdir /var/tmp/travis_bc/$TRAVIS_JOB_ID"
- echo $TRAVIS_JOB_ID >> build_id.txt
- scp build_id.txt u1249762@lab1-1.eng.utah.edu:/var/tmp/travis_bc/$TRAVIS_JOB_ID/
- source .travis/common.sh
install:
- DEPS_DIR="${HOME}/deps"
- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.tar.gz"
    mkdir -p cmake && travis_retry wget --no-clobber --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    echo ${PATH}
  else
    brew install cmake || brew upgrade cmake
  fi
- cmake --version
- cd -
- source .travis/install.sh
script:
- ".travis/script.sh"
after_failure:
- ".travis/after_failure.sh"
after_success:
- ".travis/after_success.sh"
notifications:
  slack:
    secure: L8tzicFh+EKcK21GBA2m3rQ3jmnDdqiRXIZcb0iqYlhT0V5asYvCqwlpPDUDV1wmBXqPgRJBI/jitAJlKFWu74pLTVc6FscUIDYM7S0DJfHEcufLknZx88lMmmV0IsYLQe3/s89tWoudMf1bNBo/8YWzLDffqUQ7s/rTPD9SWLppb01X0Xm158oDlA0rWETs35nuNFgJxWcSyIyIvnRNE3dHjzmBETUR9mYDsUSYlcOI44FMD8rE6emicdkqdn1zVxScobrl4Dt2bPsMfKopgIKK1x+38AuaqQa7t5F5ICnF0WfxmQ6/TcRNwIij0fDu68w/fcU8SyV+Ex5aZBKYUU7PG7ELTOq+q1geDoTlbguvFSIT4EzqErc4hbJmcUn79BKLhdjshZtGihKatntJx2faXYNYGFjwmnPFRYpqsozydztgMjzv4prZ5yoh7jhoDiGj44QcpXlQ9otM17JdfqveowMLHBYzATsxIRG93irZfXG/E3S8FvXg8mYOIEn8UK7H6i8VWL3JHlw8RbpLdNLswZOUlpEaDAeTm5tvYcw7FGH2nlZ2e5aXLxN6dTovSSRztQHbWdJTGG0N+xldBXcCiChmok4nXGReIkMc+99nZjRsiCB0R16tCNb25/p7NAVkItfVe1qRTzdnhi1hdE7LPURK4kxoFRJ6sFVuYjw=
