language: cpp

# Currently sudo is not required, NO ENV is used 

# Supported Operating systems
#os:
#  - linux
#  - osx
# Create a matrix to branch the building environment
matrix:
  allow_failures:
    - os: osx
     #dist: trusty
  include:
    - os: linux
    # Compiler is specified in ./travis/common.sh
      sudo: false
      compiler: g++-4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test # For newer GCC
          - george-edison55-precise-backports # For cmake
          packages:
          - autoconf
          - automake
          - bash
          - bison
          - build-essential
          - cmake
          - ctags
          - curl
          - doxygen
          - flex
          - fontconfig
          - g++-4.9
          - gcc-4.9
          - gdb
          - git
          - gperf
          - libcairo2-dev
          - libevent-dev
          - libfontconfig1-dev
          - liblist-moreutils-perl
          - libncurses5-dev
          - libx11-dev
          - libxft-dev
          - libxml++2.6-dev
          - perl
          - python
          - texinfo
          - time
          - valgrind
          - zip
          - qt5-default
    - os: osx
      osx_image: xcode10.2 # we target latest MacOS Mojave
      sudo: true
      compiler: gcc-4.9 # Use clang instead of gcc in MacOS
      addons:
        homebrew:
          packages:
          - bison
          - cmake
          - ctags
          - flex
          - fontconfig
          - git
          - gcc@6
          - gcc@4.9
          - libxml++
          - qt5

before_install:
  - source .travis/common.sh

install:
  - .travis/install.sh

script:
  - .travis/script.sh

after_failure:
  - echo "success"

after_success:
  - echo "failure"
